In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\chinm\anaconda3\lib\site-packages (1.5.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\chinm\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\chinm\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\chinm\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\chinm\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import pandas as pd
Data_01 =[1,2,3,4,5]
series = pd.Series(list_01)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# Using Dict, you will get index as well of your choice
Data_01 ={"key_1":1,"key_2":2,"key_3":3}
Data_01
pd.Series(Data_01)

key_1    1
key_2    2
key_3    3
dtype: int64

In [8]:
# Create the Series uisng Dictinary Pandas
calories = {"day1": 420, "day2": 380, "day3": 390}
calSeries = pd.Series(calories,)
calSeries

day1    420
day2    380
day3    390
dtype: int64

Dataframe

In [9]:

new_Dict = {'Name':["Rajesh","Sunil","Prakash"],
            "Age":[20,30,40]}

df = pd.DataFrame(new_Dict)
df

      Name  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [11]:
new_List = [["Rajesh",20],
            ["Sunil",30],
            ["Prakash",40]]

pd.DataFrame(new_List,columns=["Names","Age"])

     Names  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [10]:

# Create Dataframe from Dictionary
data = {"calories" : [420, 380, 390],
        "duration" : [50,  40,   45]}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [15]:
file_path = "C:/Users/chinm/Downloads/web devlopment/Small Airline.csv"
df =pd.read_csv(file_path)
df
df.to_excel(file_path = "C:/Users/chinm/Downloads/web devlopment/Small Airline.xlsx")

TypeError: NDFrame.to_excel() got an unexpected keyword argument 'file_path'

In [18]:
#save file

df.to_excel("C:/Users/chinm/Downloads/web devlopment/Small Airline.xlsx")

In [ ]:
#data exploration

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   First_name       17 non-null     object
 1   Last_name        17 non-null     object
 2   Age              15 non-null     float64
 3   City             15 non-null     object
 4   Airline          15 non-null     object
 5   Date_of_Journey  17 non-null     object
 6   Dep_Time         17 non-null     object
 7   Arrival_Time     17 non-null     object
 8   Dept_Hour        17 non-null     int64
 9   Dept_Minute      17 non-null     int64
 10  Arrival_Hour     17 non-null     int64
 11  Arrival_Minute   17 non-null     int64
 12  Full Name        17 non-null     object
dtypes: float64(1), int64(4), object(8)
memory usage: 1.9+ KB

In [20]:
df.describe()

             Age  Dept_Hour  Dept_Minute  Arrival_Hour  Arrival_Minute
count  15.000000  17.000000    17.000000     17.000000       17.000000
mean   42.933333  10.529412    29.411765     12.058824       18.529412
std     4.757951   5.724046    19.193289      6.859943       14.004989
min    36.000000   5.000000     5.000000      1.000000        0.000000
25%    40.000000   5.000000    20.000000      8.000000       10.000000
50%    42.000000   9.000000    25.000000     10.000000       15.000000
75%    46.000000  11.000000    50.000000     19.000000       25.000000
max    52.000000  22.000000    55.000000     23.000000       55.000000

Data exploration

In [ ]:
#df.info() — Displays summary of DataFrame including index, columns, non-null values, and data types.
#df.describe() — Generates descriptive statistics for numeric columns (count, mean, std, min, max, etc.).
#df.columns — Lists all column names of the DataFrame.
#df['columnName'].unique() — Returns all unique values in a specific column.
#df.value_counts() — Returns counts of unique rows or values in a Series.

In [30]:
# Mean : Average Value
# Median: Middle Value
# Mode: Most Frequent
# nunique: Returns all unique values of the dataframe.

list1 = [1,2,3,4,5] 
sereis = pd.Series(list1)
sereis.median()

3.0

In [29]:
list1 = [1,2,3,4,5,6,3] 
sereis = pd.Series(list1)
sereis.mean()

3.4285714285714284

In [28]:
df['Airline'].value_counts()

df['Airline'].mode()

0    Jet Airways
Name: Airline, dtype: object

In [27]:
df['Airline'].value_counts()

Jet Airways          8
IndiGo               3
Multiple carriers    3
Air India            1
Name: Airline, dtype: int64

In [26]:
df

,First_name,Last_name,Age,City,Airline,Date_of_Journey,Dep_Time,Arrival_Time,Dept_Hour,Dept_Minute,Arrival_Hour,Arrival_Minute,Full Name
0,Ram,Kumar,42.0,BANGALURU,IndiGo,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
1,Mohan,Sharma,52.0,CHENNAI,Air India,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
2,Tina,Ali,36.0,Pune,Jet Airways,09-06-2019,09:25,04:25:00,9,25,4,25,Tina-Ali
3,Jeetu,Gandhi,NaN,Delhi,IndiGo,12-05-2019,18:05,23:30,18,5,23,30,Jeetu-Gandhi
4,Meera,Kumari,NaN,LUCKNOW,IndiGo,01-03-2019,16:50,21:35,16,50,21,35,Meera-Kumari
5,Ram,Kumar,42.0,BANGALURU,NaN,24-03-2019,22:20,01:10:00,22,20,1,10,Ram-Kumar
6,Mohan,Sharma,52.0,CHENNAI,NaN,01-05-2019,05:50,13:15,5,50,13,15,Mohan-Sharma
7,Rajesh,Pawar,39.0,NaN,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Rajesh-Pawar
8,Sanjay,Patil,43.0,NaN,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Sanjay-Patil
9,Trishul,Shinde,45.0,Pune,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Trishul-Shinde
10,Sameer,Patil,39.0,Delhi,Jet Airways,12-03-2019,10:25,18:55,10,25,18,55,Sameer-Patil
11,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
12,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
13,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil
14,Amol,Mahul,40.0,LUCKNOW,Jet Airways,01-03-2019,05:05,08:00,5,5,8,0,Amol-Mahul
15,Praveen,Gurjar,47.0,BANGALURU,Jet Airways,12-03-2019,08:55,10:25,8,55,10,25,Praveen-Gurjar
16,Sunita,Patil,40.0,CHENNAI,Multiple carriers,27-05-2019,11:25,19:15,11,25,19,15,Sunita-Patil

In [25]:
df['Airline'].value_counts()

Jet Airways          8
IndiGo               3
Multiple carriers    3
Air India            1
Name: Airline, dtype: int64

In [24]:
df['City'].value_counts()

BANGALURU    4
CHENNAI      4
LUCKNOW      3
Pune         2
Delhi        2
Name: City, dtype: int64

In [23]:
df.nunique()

First_name         12
Last_name          10
Age                 8
City                5
Airline             4
Date_of_Journey     7
Dep_Time            9
Arrival_Time        9
Dept_Hour           8
Dept_Minute         5
Arrival_Hour        9
Arrival_Minute      7
Full Name          12
dtype: int64

In [22]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', nan, 'Multiple carriers'],
      dtype=object)